version: "3.8"

services:
  reverseproxy:
    build:
      context: ./ReverseProxy
    ports:
      - "5105:80"
    depends_on:
      - user
      - basvuru
      - notification
    networks:
      - mynetwork
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro  # proxy yapýlandýrma dosyan burada ise

  user:
    build:
      context: ./UserService
    ports:
      - "5027:5027"
    networks:
      - mynetwork

  basvuru:
    build:
      context: ./BasvuruService
    ports:
      - "5088:5088"
    networks:
      - mynetwork

  notification:
    build:
      context: ./NotificationService
    ports:
      - "5245:5245"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
