// <auto-generated />
using System;
using Microservice.basvuru.infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microservice.basvuru.insfrasture.Migrations
{
    [DbContext(typeof(BasvuruDbContext))]
    [Migration("20250812124339_fghj")]
    partial class fghj
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microservice.basvuru.domain.Entity.MusteriBasvuru", b =>
                {
                    b.Property<Guid>("Basvuru_UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BasvuruDurum")
                        .HasColumnType("int");

                    b.Property<DateTime>("BasvuruTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Basvurutipi")
                        .HasColumnType("int");

                    b.Property<string>("HataAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kayit_Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kayit_Yapan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Kayit_Zaman")
                        .HasColumnType("datetime2");

                    b.Property<string>("MusteriBasvuru_UID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Basvuru_UID");

                    b.ToTable("Basvurular");
                });
#pragma warning restore 612, 618
        }
    }
}
