FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
WORKDIR "/src/Notification/Microservice.notification"
RUN dotnet restore "Microservice.notification.csproj"
RUN dotnet build "Microservice.notification.csproj" -c Release -o /app/build
RUN dotnet publish "Microservice.notification.csproj" -c Release -o /app/publish /p:UseAppHost=false
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Microservice.notification.dll"]
